### ISSUE TITLE
docs: for big datasets it is better to use distance matrix in sparse format

### ISSUE THREAD

**Issue by kotikkonstantin** [antklen/diameter-clustering#1]
+ It would be great to clarify what 'big dataset' means in this case? 
+ How many rows should it be in the dataset to start to use the argument `sparse_dist=True`? What's the threshold?

So, it would be great to have some estimations about this without digging into the algorithm for the first time.

**Comment by antklen** [comment]
Very good point! =) 
I added rough estimate for number of data points in README. But also I've made some tests and decided to switch default behavior to `sparse_dist=True`. For small datasets it is just slightly slower and for big datasets it is the only viable option. So usage will be more clear with `sparse_dist=True` by default.
Thank you for paying attention to this question!
